baseURL = "https://ecstatic-jepsen-aa2dc8.netlify.app"
languageCode = "en-us"
title = "JAMSite"
theme = "tale"
copyright = "copyright 2020 Vendim Birbili Academy"
disableKinds = ["section"]

[outputs]
home = ["HTML", "JSON"]
